### ISSUE TITLE
Escalations

### ISSUE THREAD

**Issue by irstmon** [Cat5TV/nconf#3]
There was a contribution in the old nconf forum to add escalations:

http://forum.nconf.org/viewtopic.php?f=20&t=1120

Any chance to add this since this project here is active? I've been using this for nearly 6 years now - the only problem (that is still there) is mentioned in the original post:
"You can choose Hosts and services/advanced-services - wether they exist on the host or not! If you choose a service/advanced-service that doesn't exist on a host generating your nagios config will fail."

It's just a small change in the ExportNagios.pm and additional SQL entries.

**Comment by Cat5TV** [comment]
Hi @irstmon - thanks for the suggestion. I will review your PR. If all checks out, of course it will be merged. Thanks so much!
